//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoney.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bills {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bills() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMoney.Resources.Bills", typeof(Bills).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new bill.
        /// </summary>
        public static string Button_AddBill {
            get {
                return ResourceManager.GetString("Button_AddBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete bill.
        /// </summary>
        public static string Button_DeleteBill {
            get {
                return ResourceManager.GetString("Button_DeleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bill.
        /// </summary>
        public static string Button_EditBill {
            get {
                return ResourceManager.GetString("Button_EditBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find bill..
        /// </summary>
        public static string Error_CouldNotFindBill {
            get {
                return ResourceManager.GetString("Error_CouldNotFindBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Breakdown.
        /// </summary>
        public static string Heading_BillBreakdown {
            get {
                return ResourceManager.GetString("Heading_BillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to record a new bill.
        /// </summary>
        public static string Hint_AddNewBill {
            get {
                return ResourceManager.GetString("Hint_AddNewBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the table where all your bills are shown. Click on a bill to view or edit it..
        /// </summary>
        public static string Hint_BillTable {
            get {
                return ResourceManager.GetString("Hint_BillTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reoccuring Period.
        /// </summary>
        public static string Label_ReoccuringPeriod {
            get {
                return ResourceManager.GetString("Label_ReoccuringPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Label_StartDate {
            get {
                return ResourceManager.GetString("Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bills:.
        /// </summary>
        public static string Label_TotalBills {
            get {
                return ResourceManager.GetString("Label_TotalBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bill was deleted..
        /// </summary>
        public static string Message_DeleteBill {
            get {
                return ResourceManager.GetString("Message_DeleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bill was recorded..
        /// </summary>
        public static string Message_RecordedBill {
            get {
                return ResourceManager.GetString("Message_RecordedBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bill has been updated..
        /// </summary>
        public static string Message_UpdatedBill {
            get {
                return ResourceManager.GetString("Message_UpdatedBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new bill.
        /// </summary>
        public static string Title_AddBill {
            get {
                return ResourceManager.GetString("Title_AddBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string Title_Bills {
            get {
                return ResourceManager.GetString("Title_Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a bill.
        /// </summary>
        public static string Title_EditBill {
            get {
                return ResourceManager.GetString("Title_EditBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Bills.
        /// </summary>
        public static string Title_ManageBills {
            get {
                return ResourceManager.GetString("Title_ManageBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no bills recorded..
        /// </summary>
        public static string Warning_NoBills {
            get {
                return ResourceManager.GetString("Warning_NoBills", resourceCulture);
            }
        }
    }
}
