//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoney.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Expenditure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Expenditure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMoney.Resources.Expenditure", typeof(Expenditure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find expenditure..
        /// </summary>
        public static string Error_CouldNotFindExpenditure {
            get {
                return ResourceManager.GetString("Error_CouldNotFindExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure this Month.
        /// </summary>
        public static string Heading_ExpenditureThisMonth {
            get {
                return ResourceManager.GetString("Heading_ExpenditureThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Expenditure.
        /// </summary>
        public static string Heading_LatestExpenditure {
            get {
                return ResourceManager.GetString("Heading_LatestExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to track a new expenditure..
        /// </summary>
        public static string Hint_AddNewExpenditure {
            get {
                return ResourceManager.GetString("Hint_AddNewExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see a history of your expenditures..
        /// </summary>
        public static string Hint_ExpenditureTable {
            get {
                return ResourceManager.GetString("Hint_ExpenditureTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your expenditure.
        /// </summary>
        public static string Title_AddExpenditure {
            get {
                return ResourceManager.GetString("Title_AddExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an expenditure.
        /// </summary>
        public static string Title_EditExpenditure {
            get {
                return ResourceManager.GetString("Title_EditExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure.
        /// </summary>
        public static string Title_Expenditure {
            get {
                return ResourceManager.GetString("Title_Expenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not recorded any expenditures..
        /// </summary>
        public static string Warning_NoExpenditure {
            get {
                return ResourceManager.GetString("Warning_NoExpenditure", resourceCulture);
            }
        }
    }
}
