USE [master]
GO

/****** Object:  Database [MyMoney_DEV]    Script Date: 13/03/2017 01:07:32 ******/
CREATE DATABASE [MyMoney_DEV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyMoney_DEV', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MyMoney_DEV.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MyMoney_DEV_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MyMoney_DEV_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MyMoney_DEV] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyMoney_DEV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyMoney_DEV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyMoney_DEV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyMoney_DEV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyMoney_DEV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyMoney_DEV] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyMoney_DEV] SET  MULTI_USER 
GO

ALTER DATABASE [MyMoney_DEV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyMoney_DEV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyMoney_DEV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyMoney_DEV] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MyMoney_DEV] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyMoney_DEV] SET  READ_WRITE 
GO


